# Generated by Django 3.2.16 on 2022-12-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='runningkm',
            field=models.CharField(max_length=200),
        ),
    ]
